package myblog.pojo.mapper;

import java.util.List;
import myblog.pojo.po.FriendLink;
import myblog.pojo.po.FriendLinkExample;
import org.apache.ibatis.annotations.Param;

public interface FriendLinkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_friend
     *
     * @mbg.generated
     */
    long countByExample(FriendLinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_friend
     *
     * @mbg.generated
     */
    int deleteByExample(FriendLinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_friend
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_friend
     *
     * @mbg.generated
     */
    int insert(FriendLink record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_friend
     *
     * @mbg.generated
     */
    int insertSelective(FriendLink record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_friend
     *
     * @mbg.generated
     */
    List<FriendLink> selectByExample(FriendLinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_friend
     *
     * @mbg.generated
     */
    FriendLink selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_friend
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") FriendLink record, @Param("example") FriendLinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_friend
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") FriendLink record, @Param("example") FriendLinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_friend
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(FriendLink record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_friend
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(FriendLink record);
}