server:
  port: 8080 #内置tomcat端口
  tomcat:
    uri-encoding: UTF-8 #URL字符编码
  servlet:
    session:
      timeout: 30m #session生命周期

spring:
  datasource:
    username: root
    password: Szz18005800918
    url: jdbc:mysql://localhost:3306/myblog?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    # druid数据源专有配置
    druid:
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      # 配置监控统计拦截的filters. stat:监控统计; log4j:日志记录; wall:防止sql注入.
      filters: stat,wall
      maxPoolPreparedStatementPerConnectionSize: 20
      useGlobalDataSourceStat: true
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
  thymeleaf:
    check-template: off
    check-template-location: off

mybatis:
  mapper-locations: classpath:/mapping/*.xml,classpath:/mapping/custom/*.xml
  type-aliases-package: myblog.pojo.mapper
  configuration:
    #   log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    lazy-loading-enabled: true
    cache-enabled: true
    aggressiveLazyLoading: true

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  pageSizeZero: false # pageSize=0

# dialect: mysql
# offset-as-page-num: false
# row-bounds-with-count: false
# page-size-zero: true
# reasonable: false
# support-methods-arguments: false
