package myblog.pojo.po;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_friend
 */
public class FriendLink {
    /**
     * Database Column Remarks:
     *   友链id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_friend.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   网址
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_friend.blogaddress
     *
     * @mbg.generated
     */
    private String blogaddress;

    /**
     * Database Column Remarks:
     *   名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_friend.blogname
     *
     * @mbg.generated
     */
    private String blogname;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_friend.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   图片地址
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_friend.pictureaddress
     *
     * @mbg.generated
     */
    private String pictureaddress;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_friend.id
     *
     * @return the value of t_friend.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_friend.id
     *
     * @param id the value for t_friend.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_friend.blogaddress
     *
     * @return the value of t_friend.blogaddress
     *
     * @mbg.generated
     */
    public String getBlogaddress() {
        return blogaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_friend.blogaddress
     *
     * @param blogaddress the value for t_friend.blogaddress
     *
     * @mbg.generated
     */
    public void setBlogaddress(String blogaddress) {
        this.blogaddress = blogaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_friend.blogname
     *
     * @return the value of t_friend.blogname
     *
     * @mbg.generated
     */
    public String getBlogname() {
        return blogname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_friend.blogname
     *
     * @param blogname the value for t_friend.blogname
     *
     * @mbg.generated
     */
    public void setBlogname(String blogname) {
        this.blogname = blogname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_friend.create_time
     *
     * @return the value of t_friend.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_friend.create_time
     *
     * @param createTime the value for t_friend.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_friend.pictureaddress
     *
     * @return the value of t_friend.pictureaddress
     *
     * @mbg.generated
     */
    public String getPictureaddress() {
        return pictureaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_friend.pictureaddress
     *
     * @param pictureaddress the value for t_friend.pictureaddress
     *
     * @mbg.generated
     */
    public void setPictureaddress(String pictureaddress) {
        this.pictureaddress = pictureaddress;
    }
}