package myblog.pojo.po;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_picture
 */
public class Picture {
    /**
     * Database Column Remarks:
     *   图片id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_picture.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   图片地址
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_picture.pictureaddress
     *
     * @mbg.generated
     */
    private String pictureaddress;

    /**
     * Database Column Remarks:
     *   图片描述
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_picture.picturedescription
     *
     * @mbg.generated
     */
    private String picturedescription;

    /**
     * Database Column Remarks:
     *   图片名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_picture.picturename
     *
     * @mbg.generated
     */
    private String picturename;

    /**
     * Database Column Remarks:
     *   拍摄时间、地点
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_picture.picturetime
     *
     * @mbg.generated
     */
    private String picturetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_picture.id
     *
     * @return the value of t_picture.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_picture.id
     *
     * @param id the value for t_picture.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_picture.pictureaddress
     *
     * @return the value of t_picture.pictureaddress
     *
     * @mbg.generated
     */
    public String getPictureaddress() {
        return pictureaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_picture.pictureaddress
     *
     * @param pictureaddress the value for t_picture.pictureaddress
     *
     * @mbg.generated
     */
    public void setPictureaddress(String pictureaddress) {
        this.pictureaddress = pictureaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_picture.picturedescription
     *
     * @return the value of t_picture.picturedescription
     *
     * @mbg.generated
     */
    public String getPicturedescription() {
        return picturedescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_picture.picturedescription
     *
     * @param picturedescription the value for t_picture.picturedescription
     *
     * @mbg.generated
     */
    public void setPicturedescription(String picturedescription) {
        this.picturedescription = picturedescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_picture.picturename
     *
     * @return the value of t_picture.picturename
     *
     * @mbg.generated
     */
    public String getPicturename() {
        return picturename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_picture.picturename
     *
     * @param picturename the value for t_picture.picturename
     *
     * @mbg.generated
     */
    public void setPicturename(String picturename) {
        this.picturename = picturename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_picture.picturetime
     *
     * @return the value of t_picture.picturetime
     *
     * @mbg.generated
     */
    public String getPicturetime() {
        return picturetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_picture.picturetime
     *
     * @param picturetime the value for t_picture.picturetime
     *
     * @mbg.generated
     */
    public void setPicturetime(String picturetime) {
        this.picturetime = picturetime;
    }
}